--- # FULL INCLUDE TASK EXAMPLE
- hosts: apacheweb
  user: test
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
    - include: plays/packages.yml
    - name: verify telnet is installed
      yum: pkg=telnet state=absent
