--- # TAG functionality example
- hosts: apacheweb
  user: test
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: install telnet and lynx
      yum: pkg={{ item }} state=installed
      with_items:
        - telnet
        - lynx
      tags:
        - packages
    - name: verify telnet installation
      raw: yum list installed | grep telnet >> /home/test/pkglist.log
      tags:
        - always # verification # this ensures tag is always run. only way to skip is use --skip-tags
