--- # WHEN playbook example
- hosts: apacheweb
  user: test
  become: yes
  connection: ssh
#  gather_facts: no # We need to gather facts here
  vars:
    playbook_type: conditionalexample
  vars_files:
    - conf/copyright.yml
    - conf/webdefaults.yml
  tasks:
    - name: install apache on debian
      apt: pkg=apache state=installed
      when: ansible_os_family == "Debian"
    - name: install apche on fedora
      yum: pkg=httpd state=installed
      when: ansible_os_family == "RedHat"

